#!/usr/bin/env bash

timeout 10 slurp > /tmp/slurp.txt 2>/dev/null
if [ $? -eq 0 ] && [ -s /tmp/slurp.txt ]; then
    grim -g "$(cat /tmp/slurp.txt)" - | wl-copy
else
    grim - | wl-copy
fi
rm -f /tmp/slurp.txt

