#!/usr/bin/env bash

# killall swaybg
# pkill swaybg
# sleep 0.5
#
# swaybg -m fill -i ~/.config/wallpapers/birmingham-museums-trust-nbneQlI2M1A-unsplash.jpg &

wal -i ~/.config/wallpapers/203514.jpg
