#!/usr/bin/env bash

selected=$(find ~/workspace/github.com/mitchan ~/workspace/bitbucket.org/spiaggeit ~/workspace/bitbucket.org/spiaggeit/contexts/repos -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename $selected | tr ".,: " "____")
tmux_running=$(pgrep tmux)

switch_to() {
    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi
}

if tmux has-session -t="$selected_name"; then
    switch_to
else
    tmux new-session -ds $selected_name -c $selected
    switch_to
fi

